spring.application.name=Notification-sending-system
server.port=8082

spring.cache.type=caffeine
spring.cache.cache-names=usersByUsername,usersById,notificationHistory
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

app.jwt.secret=${APP_JWT_SECRET:U2VjcmV0S2V5Rm9yTXlNaW5pRVJQU3lzdGVtMTIzIT8=}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
app.bootstrap.admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:true}
app.bootstrap.admin.username=${APP_BOOTSTRAP_ADMIN_USERNAME:admin}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin@example.com}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:Admin123!}


spring.datasource.url=jdbc:h2:mem:notificationsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

